stages:
 - build

Ubuntu-Subproject:
 stage: build
 script:
  - export CMAKE_EXTRA_ARGS="-DCLONE_SUBPROJECTS=ON"
  - bash .gitlab-ci.sh
 tags:
  - ubuntu

OSX-Subproject:
 stage: build
 script:
  - export CMAKE_OSX_ARCHITECTURES=x86_64
  - export CMAKE_EXTRA_ARGS="-DCLONE_SUBPROJECTS=ON"
  - bash .gitlab-ci.sh
 tags:
  - osx-sierra

Win7-VS14-x64-Subproject:
 stage: build
 script:
  - call %ENVFILESDIR%\Boost-1.64-vs14-x64.bat
  - call %ENVFILESDIR%\zeromq-4.2.1-vs14-x64.bat
  - set BUILD_GENERATOR=Visual Studio 14 Win64
  - set PATH=%PATH%;"c:\Program Files\Git\bin"  
  - set CMAKE_EXTRA_ARGS=-DCLONE_SUBPROJECTS=ON
  - pip install pyparsing
  - bash.exe --login .gitlab-ci.sh
 tags:
  - win7
